name: CodeCov Report

on:
  push:
    branches:
      - main

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
