name: Deploy

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: unbuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: NODE_ENV=development yarn lint
      - run: NODE_ENV=development yarn build
      - run: NODE_ENV=development yarn test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'kreative-id-api'
          heroku_email: 'armaan@kreativeusa.com'
          usedocker: true
